apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:xhzOU/HuXAJAi3k6I9qWNlDxMC8SV3FH5aJZ+jjq4VS/8h98oMjSjA==,iv:QBXW6OdVFzKO0Bdr/Wriya18I1bJmF5mkUq7u01rbZM=,tag:qjM4x43hObbsekko1eFlnQ==,type:str]
sops:
  age:
    - recipient: age1dlagmajl96rsfff84arhj2dd97kpy64wjp6dxgjftvm8v0fy2erspglp3s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOS2F6UkhiVldQcHJPUUJF
        YytoZVNOeHhrS0JXUXhHR2NGNEo3S21uMHhvCkdJQ1R5K0g5ZThudkhGNlc4NkJE
        K3o4cERZckVJSGRqQU0wUWNuVU5NdXcKLS0tIEd4UHRETFNRaE4ySjAzSG9yaDUz
        TTYwVEZsazJOaWNCVWoreWpwRlBmYXMKuusL2HFWUriEuOKCTWcjyzGOgOytVTQq
        YEJd/DJVBQVEjIQVTAYS6xKRmWh72lvjEf/tjLt8UKUc5AL8pxz1dA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T01:18:18Z"
  mac: ENC[AES256_GCM,data:doID+14tpW585mUTq2rqvH6ryAx1vAX6X0KHWl23117UZIhnEu6/zhFFOi1AvsbzXvQlfqSKz/36svGBYllUuvtktCocOa1wMxCQ9GHX0wqjNNfGxdCkMjd1wgSOS7Eu13RY4KpSWi6ffRixwLE4X1BREl2a1Ax3zMlhTCQbWFU=,iv:nE+BiaJFtf1Cgw6/rVWXSSGef4b+PtmVFzP02HV28ko=,tag:MF/+trBS6eBMjuX4JIVwdw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
