apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:uO6+QDF83odIWHtApAoNXtrXtJvYRATc37F/xmzLbEyXBSwbUYBNpA==,iv:Dr/UH4jb6zVwGyPi8qrhAOc6NPkM2D3Ql0AvXKvptTY=,tag:gmp0caCn/l2SoyQ9WIvR9Q==,type:str]
sops:
  age:
    - recipient: age1dlagmajl96rsfff84arhj2dd97kpy64wjp6dxgjftvm8v0fy2erspglp3s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMT2F3d0hDQTBPZGtFdFkz
        VnpMK25UV2tqQ0o5SGxPNFgrOFRqbzIvUDFNCi93a2xyQXpDeHVpOUZWTTBUNlVs
        T0k5b2pZaUpIUHIvT2x2QzhWdEQreTQKLS0tIElFR0VHT3RteVBNUU5nRzkxYXBF
        SWtwbzBZR3ZseGNGR0R0WXpCNWdaeWcK7y1C63QwksTJzpaO9v563tQCF0Eem1Vq
        I3VDjbeloLU0KX7b1YZdwSTmbmvtUnYo/xZFX/3a/5hNZHT5dmt/8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T01:16:47Z"
  mac: ENC[AES256_GCM,data:f9YnA418PuoZTrukwI8l79su3WO2BEoWWzynHhLB4BJBk+MMnNfJIWjdoIPBc7iCKOZYB6F/O+zqWL1S3KxoUL69cTPvEACFZNtMZlBrN9c1CmmOCAqqwcWWl5QdJU9/g0gI09OnzBiP/GXzMteLUitAZMn5l0+j0sqy5zCcMlw=,iv:eM/XRqYc2pCuQzaQOzCclfUaRb5TiQeppypdge3po0E=,tag:7yU/0sHCWtxURmqewgyrJQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
