apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:UhJnO+zSe2fgn2tmT8usbwR8AMo+pLLfYbvvSVmFc0FRRPZoW2F8tQ==,iv:aYUtzdI2lZV11W3BkmQctKCbDDl+0x8hwMTeYVtf/Pc=,tag:OpkIgvJD0ZiTlh/o1fF7/Q==,type:str]
sops:
  age:
    - recipient: age1dlagmajl96rsfff84arhj2dd97kpy64wjp6dxgjftvm8v0fy2erspglp3s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbWR0d0lpV083aE0rVVBy
        eG9mS1hIZmxsSnBBeUNWWUdTNlRnZjBXaWhJCnBmUEUzcThwN2pUNThTK0ZPbDVK
        WCt1bnJxRTBIdzhYeksvNjlWZjBMUWMKLS0tIE1neVg5WTgxbmVkUFBqR3JWQkxz
        L0lMVHhOUkUzZWFQc3cxSnJtRzI4OWMKMMfHJskUGY+MTV5vEvYY2x60RsIf5A2k
        UbvzvrNISRweEtoEtfQfe9lgb+flZmP8jojwPRDnQCW2hfZaGm/cWA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T00:20:52Z"
  mac: ENC[AES256_GCM,data:QeO+ixvKmyBWwm2c8JX0c3KF4iIYHNcqn14fetzGehMeMPRo8JaujEbQVNfsUbvFvkd5nVR39SEBOtweGmuEWF/g5Tdo89vbPQUcRzJyWOc7P2Dgb8DCc2SfBKkuKrKOvzHstHHX9UKrnKNV+d8vw81wqZfnyknysNqn2dMRLG8=,iv:PjpMfLjZ7GohRxXA+XlM7EPUBDGgvrLcrQN6g1BSya4=,tag:aox+sWhJM/TFdVHHzgGDXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
