apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:9CFbG5pAKdNcqTiSxbwt,iv:XeSzWfwOOokRqRQxjjE/AHbe60g/G6NTvPyNem3ldWw=,tag:QK3MPV6gV5M4B0/ZZ8p4pg==,type:str]
sops:
  age:
    - recipient: age1dlagmajl96rsfff84arhj2dd97kpy64wjp6dxgjftvm8v0fy2erspglp3s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXanJ3RGJyaUZMdlJ5dXht
        cWxzOFhXVytjWmdoWWRsN0dsc2swc21ISGxnCkFydGNSUWNNYklYUSt1KzM5QkM1
        WE0vcGkyUGFzMTNSa2ZxL2VHMXFwRk0KLS0tIGlLM0VyMmNDOWY2cGJlTUpXWnhq
        TVdueXpHSWtKd21WTGRrY3UraWUyS28KAAt8iK6OzrOEmW7dGmuW5ls1jSKZIZyE
        Me6fCy9S0C5IxxdBCQQ8F30NXlXpFHL/PKp86uD3tk7NruZl7pYzGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T00:20:52Z"
  mac: ENC[AES256_GCM,data:Ssy/6JM774AhujNzHZUvmAyaIwosEiIlFaDbRR3I0FTK3Sb29Fsp0A648JnzGAFvghhq95YcCPZjP3JC62ljxzdSCeTfwQE0rp9imKYuhF4IdM/pP1llZTiZ8x+m/pviCrswE6jOVzUC04Bi3erw2/mlQp7SFkixpZavG7sl50Q=,iv:yPor1LldOG/g9dyhIhwCBcCqRKiCOo0+Q1P6ZYWiLiM=,tag:3dVaHMIv/qDBuA7QFmT9GQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
