apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:YXFwaRxie1Y+Y+NPV55h,iv:EH45Zz9zJOhq7NDFauL62kxX+0fgJ6pZ5pFZta288o0=,tag:w8eQEAUZJXwrFplzkwuA5g==,type:str]
sops:
  age:
    - recipient: age1dlagmajl96rsfff84arhj2dd97kpy64wjp6dxgjftvm8v0fy2erspglp3s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdGR0cDB2MGhXZldXeWQ2
        Und6cVMrbVNMK0hzYW5ENEdDczRLYitXMXdRCjd4Z09sejBEdFNaODIxSEpTT1VF
        NVI4R3RpbThJMnpjTks4UG5VOXVKZEEKLS0tIGIzYm9YZzUrR3E5Z1crQytnQzhJ
        TTFhWEsxL2J0OHpQcHF5TGpYVkxKQ2MK31bW+INxspiD/+kLuLOPMBgxkdbCdz5W
        qpQJ40GfmpEBrVNc/M0XxJXNAf6zP64RnLJSNoNuGUsqobNR48M1Og==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T01:18:18Z"
  mac: ENC[AES256_GCM,data:0M+6LPN9QptvyrcI4Ig+6sY46mC9cg+mo3giW4HYeg82qw41a5/BXWuZ1b5S8a6irVFR6ZcMDSCtaAF+UPZUsMNpQoHfc4JGFv266OLU3qa6G+rOfay2IZJ7uoz7bPTSpoDw0r4U9TNFf3D5NkvE1tzFGHaCPWrionsMeas7A9k=,iv:obD5o1+ar3mY0Q4A7kdtRKG3D83zbOA2en3kBNA/5mI=,tag:7A5ouGndSiQHyF/SjqvTng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
