apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:qEf/4gHV5jPXRVaZxE99,iv:Z3fCcPfRHxHr/WM+KXU6zP/JXpJIU8jdNhkH7s+A8QQ=,tag:kkTS1bmLUhjRM5Vvg1hDDQ==,type:str]
sops:
  age:
    - recipient: age1dlagmajl96rsfff84arhj2dd97kpy64wjp6dxgjftvm8v0fy2erspglp3s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRjdKY2NUdXFydGdjTW9Z
        RlVmdzJURWFEWFlBSWIzakpsUlJUOGZxUkU4CjkrN3REOWJ6ZFNuaVB1aWViL3pa
        UnZqMTNENlhISnovMEdBa1V2Z0RjakkKLS0tIGQxZzg1ZHdnMVBnNnBrLzhTYWxj
        ek1JQkF1Mld6bVdsSUowZkowd3JwZ2cKOKj7RBLylqOexb7As40xVvV88cDG8dol
        EusFmyoXAc+52Sk2K5ejyPypIy0rhbrYqTIJIGlQKkIq/rawgcckew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T01:16:47Z"
  mac: ENC[AES256_GCM,data:0k4wgSGrqasSdU+GaDiHjc4oNPoq6odCTOfrAZO/VPa+tshcVO2tEd7tuLXFjzFrmXMmYFgGjhWH6msaU+4yGlorA85DAoZ5F2roTFjBxdP+uIVDGUaR3sgBm7crbZ+MIUNwoCgzrZEXLiIk2sxpRzQuVRiG94cBY0+l+ZQjIfo=,iv:2Q7jLdMmbFu0/1f0UG7Wx3HbmPgtU0dZKOx6Yop9HMQ=,tag:LolBcb4V2lWxRKThUxUCDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
