apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:G2Ge3+2Xd62toZYpx93lvL7KmPO6YTt8d8e5Wtio7Os=,iv:g90Rf8JdPJJ9y3c64/KRLWyxJlq+wiJ58xA6Rm2MIjg=,tag:8VP9wuIIi4SGqSbgpJrhVQ==,type:str]
sops:
  age:
    - recipient: age1dlagmajl96rsfff84arhj2dd97kpy64wjp6dxgjftvm8v0fy2erspglp3s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGL0VHSFlvR29ZVWExS0Q4
        UlgvV0QwWmZkWk0raTJmSGpwN2UwcUMwZ3dZCmx6QUc4dCtWWDNSb3NmNGJWWGpt
        U2ViWjEvRys1ckJENnJxaityRjVkNW8KLS0tIFhtOTVrL0lDeTZLdE5INUpjVS96
        Um9MdDMvSHBRbVdGTGtoV1B1Z25qTTgKylZHBWUZn/RiGQYB4XW7zbKs7Livnzoq
        B+4GT55cpaL26VK6PRapkTuEAkW/AU1PNZvx0huPDT2FJMBR5xkTRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T00:20:52Z"
  mac: ENC[AES256_GCM,data:qmGf3sBJj7cUW9yAqmGdkgLgMdd6/neuKE2mQ8WD+LY/HDZVLK7WoxppbeQj357WqIkrftb9kzKHa1xguCqgFWZgXh4VOhiiExaiB4ExbRGfpHXNEvKbKFIGnd6Hrj8JPTBthfer9no8n2uiXhOf8sOJUjdAfeHuTuNnW8pfrTQ=,iv:oCMYuzZi/KstOAxswjqt4ybsZ1HABwDWhYR/FXn7iHU=,tag:eUY9n/WLH5lPH4RphL4PYQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
