apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:VJFwFyu9DdVb3D4fcHuAeU7xDfLs8W+x+Pl3mUX2a7Q=,iv:Ysz6v8QnGdccL7HGC+CJrb0ZcIf4AoSOO9rNOikUn6U=,tag:OJy3Md9vuX5wHknAZtmIig==,type:str]
sops:
  age:
    - recipient: age1dlagmajl96rsfff84arhj2dd97kpy64wjp6dxgjftvm8v0fy2erspglp3s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WW9IcWhhMEFENlp4bDFa
        dkFYNGxqU05qQnlBRU5uQ2NjRlF6L0JoOEhnCjhTMUxYcUVEY1EzVVZxUW1OdnNj
        c3lmUnVkOEltVFFoblFiU1NhSU1IaUUKLS0tIG5uSXpMbWkvOFFleHpsYndOd2ds
        Ti9QOFdqTC9DdnYxQm02V3R0dUIrOVEK4PXc5e161IiWaDBzDI96ZoicZf3Bkfok
        +Qt9ZI9H4aioTwFVsgGvuWTJ5SOD9g5fz0cJ8a4QwZxuwtS3zrDv7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T01:18:18Z"
  mac: ENC[AES256_GCM,data:Xb+DTin9f24ixg0XK+A8fSTdVkcTMKiWjJsTD2wm4jhSJNWGuL10cjLBlHwHTyylTlxxTVhSQVoqOcvy7cHmdcxiaM0YeWL32QVGwuf7DGHnM4ZG+DWzb3calxwd3qUOus8Z1UGaY3930dsr+1NgYhSlMj7Y0c0Ct3A60rrEIh4=,iv:NaPRJHIw2D10JK6Fs3GPeQpzOvJbeWebnJ139QWkpe8=,tag:SbctVTesWRA3u3oQ+9hswQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
