apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:KLmJ4TkFMBvGGENlSI0qNXkou1SRMfrOv0+Dh9eBTLw=,iv:njPS6fVKl2stuFnGJB9T+XU4RO7SMJkRfLuYgfO0kqo=,tag:2cU+Vhq5t0uQ7aFfLgRN1w==,type:str]
sops:
  age:
    - recipient: age1dlagmajl96rsfff84arhj2dd97kpy64wjp6dxgjftvm8v0fy2erspglp3s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQng0d2VQV1lWaFRjVXlw
        STk3dHhHTjhIQ2F1bnBNVkVaQkJURTFRVWpFCjM3VTFPVnh2bzRnMFZvYkVKck9m
        QjRlS0I2SFg2SHJxcVloQ01kSUxnbTAKLS0tIGRoNjBRVW5VT2l1dW1qQlVLRTNZ
        eis5Tk9LZjZxWmNpcjdTeFBQMVN0UVkKT3RYcXGZVLOgWgMcKGAL8j8YKLThkNqm
        R97wCP9aXy2Pn4ATaMH1mDINUiERPA+GR5Kv+LwiorYrsjHTL1z6Aw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T01:16:47Z"
  mac: ENC[AES256_GCM,data:ARpAi6/mQR9hawLJ+Cq4l32wPTJ0rqV8sBpFWlBRMk0mD0c02KczEp67f7pmJASP/SPNdfnATey80098q5Ki7THeggT8aFzGRslNuJFbC8wJPqy0aqBRFQVn0XN79jctYykoZaIaIQLENtNFPIj9btdE+2QAw1DYmfCOl7CDE9Y=,iv:TsvOPjyKv2Q/V8W/mUeOTW80TqEo71vddOaHTTNFBYM=,tag:UnTA9UAzx68u0gV+LzcCcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
