apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:mDRC863gpjfr7aQ6fm2ZzDiVZL4jnTkbH+P4gqA8TKVMX/pVvCW1VBsQnnVaAKfIdnbrLZTY4eH79Me6ydqw16iGNWOAxdf7NlZ52k5+Emt2vNuEJ5DbdpIDnGEkPCq6x6GaEm/myhLMXacrYlIbg5SN5enDj6+ONAJKNBYt5h4tdEaKK9x2eCQ1VChPFlbjeOuHb+J2iwh5eXyoNZoN3FtrF+rS+Ih03dxaBP+W+XGldJZz,iv:HpruwOWneXxhYxcTVQrBLkEGynBU8of0QAT1EpnH+ls=,tag:+W0arNFQyDWoLXFP6nwE0A==,type:str]
sops:
  age:
    - recipient: age1dlagmajl96rsfff84arhj2dd97kpy64wjp6dxgjftvm8v0fy2erspglp3s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUW1oSXk5WCtaY2ZraEpP
        eGJtQitOZmJGZzZxRnpJRW95bFlSajE1dWpzClRxZVd4Tmx2WDVZYjdZYlRwTlRq
        Q0lwenN2YTRoa3B6RjZCM3ZVRUlYeHcKLS0tIFNRTVp1VE41b1RPMUllTm9vWUQ3
        UlNlSXRYdXU3SHRlM25YNXRocTkyNmcKAKPoAO9zIOD9A0F4XULVlg14lG5Jn4uu
        fh3VaculbeprK+JcOJqDYeeLMWCNJGoqwoguzejJRLWemVu/jX72oA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T00:20:52Z"
  mac: ENC[AES256_GCM,data:iveapHxpHnsqfOjAirwFHG/hDlzvI/EgfzXa7PK5Zq9PVyGjv3440wDIHu6JQ01yf5YgIjX7HjvXLdFPinn5TP4+jXnL0iMkKpZCjnBDuQSZv2FlTQBxpBPLlE08s6dYPdw3VEJsy/sPzY1xXx2VUzc+8D/E4YQQbQAFfVrVt4k=,iv:Lfmlg31XBxklDgEEseon+FPvzHPwJgmu/TWzBf1FiVE=,tag:781M/bIJpE4R22TcYAxLHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
