apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:JgOSB2qzStadaaByP8d4j8vZHmMHftZHNLcmpbfQatLiVYnC6Ox3rltvXivDXgjhgZsPrZepFmEf5uQLNGvE7QK5ekCYYidZshAy0sYzVH/nUPIQTw6E3y2dbzBL2N46/ufAI7X4ts78/G8tG4q/0stVMocMCjWu9MQlPOw3K1bTWK7x76JcHRgGXl4S6O4LyDLB3gNnk/mSVZfc4wD2F3SOpp9Uv2UWpgm7zmA4n0Re8KTn,iv:0eR/JkcfOa8thzbnf3xUK7zXRKmQCZqWHYmguDNsWDQ=,tag:xa0Vwu7estZ9DyEoBU4ulQ==,type:str]
sops:
  age:
    - recipient: age1dlagmajl96rsfff84arhj2dd97kpy64wjp6dxgjftvm8v0fy2erspglp3s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBM2RRZXVzWlhBT2JtRU9W
        UTZVclEvT3lRdXRQd000NlRkTENVdHdVUlM4Ci96ME9oT0RRSk9vOHR0RjB5d0Jv
        MTZuNjNCK01acG5VTnAwNUZSOEd0RkUKLS0tIENxVnZwUmtQUDRHN3NUK1FrdEZ0
        aGtGV0hOdmo4WUNXQmpwcVdNbEJwQTQKX3rb5hPKuWYeDfqRn9Z/sEHpnzNVoswZ
        MvtqDC3F5RuxOh8kC5SeHEftvtIejL9ZGu0oLlETm6Myfq2Gpz3jBg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T01:16:47Z"
  mac: ENC[AES256_GCM,data:HBG5J/6svePdaCIChBhIywGfVp6Rkpe1xfS00g35MoCjh6T7B3v/0cFkB+UbgZSikF+Dov+yc8rPmjbmADMM6tyLNa5mDWo/Xd3zesUFyis0x0GGmxHR5zWojglpEfK3383bHSWP4qnqAGSJL/qwMRkDQWp9ZpIRLuYbmCRAqJU=,iv:RWG5+5lPP8aEeOdI5BwPkDB26qaPculQR3jsOeCoTcY=,tag:kqrEJnXI0OqbvxsfytslxA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
