apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:3OStYfGXgW0Gc5pvEhudNzD3aeutdLQ39N7hQyx6O2/jV1pB34GQYdpXW6+2Uw/jnAn1bM5ZGTSn/sgH3n9Wy4hxMUAfP1bctJOQpIivSqYgjOoOjgEBjq3D6StwOPZ8frtAUwAKNCOvlCC703FoxeZePiDeRme68cgx2x2pQFeNiZGt7lnZESs8xLArQwfHVY+MMGRYIJmQxMCwtr3PcBhuje4Lw5z3rTvD9U2tR/UsTm+G,iv:SF+bmzaI382KOMKtihvkXrIsNgMojcXMS0ihS2VR5bI=,tag:iUgQJcROXjSZ4Vg+sLjkKw==,type:str]
sops:
  age:
    - recipient: age1dlagmajl96rsfff84arhj2dd97kpy64wjp6dxgjftvm8v0fy2erspglp3s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQ0VBL0I4Yi82anlxQy9y
        SStLR3BEZHBRSjZYS0hQSXdISnpFMkl4U0ZVCno1VnlmbFRZNGh6ejh1UEVxcWNN
        SndMTG5CVmNtTWd0bm5pcXlSL0lydU0KLS0tIGJOQVErUEs1WFBSdTlDNnhJVExJ
        Uk5wRmJ2ditJMmtVdE1Gc0VYSzhDMGMK6zJwV8ncOCjc8UMGmtLEMP94s9G3rMQz
        N2VtTqvdMZlJ5936FhnyKbPghlQ118E20ToQO1lUiOd+0Qz1vmgAzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T01:18:18Z"
  mac: ENC[AES256_GCM,data:yHpyWdvNz47jPWdQaDgCWazl+oItAqiJhoOq6WpVFxGUpZvMTdiBd4iQjo2Fhm8hKFWLTFnC8IW6oQyG5CJS4Yr/8hIGpr6kxtJx6pQdNH4ESUpOIqlEaJTccEBQjrmn453+7XeKMmMaLCPc1TMpwARQBXN1ETuuXtF1RlPmyFE=,iv:EqRWNajWP3YNLk2z4ekX5cv1uUzAR5JFS5HY4T0MXwQ=,tag:X8+IsngyBEp8YkGIBPY75g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
