apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-secret
data:
  1password-credentials.json:
    verifier:
      salt: ENC[AES256_GCM,data:3HWmht7UWJ9uSjcmcHhCNfadJNuRbg==,iv:qdPKqMw0dJWlOEY0rG+Y+lSqDtpQqJWxs6XNoY4kI3Q=,tag:xa/5zItRTJ8tkkZD8c8OKA==,type:str]
      localHash: ENC[AES256_GCM,data:55+8T26IfPDfhqcuXe/Ji4jNLz1tEqcsOoKInB3lUeaItdLFg64fLpOydQ==,iv:fT8CcplzN4RCLY4tS7BVXHgIgsOX//vsZPk1rOC8D0k=,tag:8meNYh4o5lS2j+ygo9qc1A==,type:str]
    encCredentials:
      kid: ENC[AES256_GCM,data:wKQ+ZhwSWbiBE6gsSjIUTqk=,iv:2MdL3IDjmELdHdDYc3KpZi0N6DCI90NVceyOgT8YHGE=,tag:Al8Hjz4sRvF7R1AHsqiW8w==,type:str]
      enc: ENC[AES256_GCM,data:7VG9V+AvBQ==,iv:G3dshOJCMOuWgsSz0A5gNKTWjAG6Lc3bxRQJtI9JBjs=,tag:cO/rgExh9N++Lbroy02hvg==,type:str]
      cty: ENC[AES256_GCM,data:YehjaPVDcu6Ufkk=,iv:FY0dJsCn/2YRONYG4obuaf4iYYmpwktdbouK+c0b1Ww=,tag:9RXk+3moSrWzB+ZQ88kLZA==,type:str]
      iv: ENC[AES256_GCM,data:PTqrdBrykLiQYHHgTGa2bg==,iv:Y1Us4x7gTPvuXVwoqlEABZFEqqFHdyDjAoaa7MsBO/w=,tag:yK/VR80gE+ckC561RmioOA==,type:str]
      data: ENC[AES256_GCM,data:OqFAPjgJRLXEWGz9YDAXBW4MaNTizaFVLuEZnQWHMIPNmsED7NQhzQL43a4IIP+EjkqUPL5zY+y3oZpoxuBhDG3BRYnSxCpj+JzEX4wjcstjZWTYmIHWIoBUhcZl8ChG5dPl3meZbQ9FMj3muEyC1yGC9ikN0i1VYVtPhMKqg9sAT0diQOZ0HGYkSNZIzsSI59jqdAdldCPbJz2uo8wbyXs4qeKMSKL60cTuD5DTW1g29x+TKmZZyvbg0M2qNcHOJMEDgvt5a4cfG85fErjjvzCC995Qp3dM/xWvWSn7iy4vTNtBepXzOUZEGDIgickLvbBVupOWRQmKINmmxAjNYWkJ5Y5TI1EhwSIYBXeX7QpS4nm2SBFtc3pOfX1T+66bCbvTpTeGsc9GCaXRuXzVt9PjHGbxwmqaSxVQ2+eDiqpenfwHsRo8YNDiEEAod6iBkH/3uRbmieN5hC8Kz0sJzP4H0d15QbMJIdCrEfUk6EBjk/9J2EEUxm8uLyu2a8fhol/ovyzfclGW3hZzxodXD4GA2ZsgTGfOIKDkipwbVntcn4NrCtU9BNM/1245TduyXfC1iGXuvFyECpdHz83Kg0mflUl1/kuaSsbu1/JGE6KHtgenqRS2wXbPjKRu1TQwVU0N7qPPvquyLCsFLQnghPi0Fp2sZTAnFyy+ZaqTI+68PNsGA/qE0VmeF9CBFoE5u29AGRlj77eE+oljT4x60fQb9lp2f3KHx3/6KRBj6CWP2BwaiSd+Ip6dvWFE5EIRKB2lnz0moaXdhwN+V6MkwfCRuF73JaetxovMrEhtT68JCZrOxZKqZ6TOnWrbu203uBsbqw2rV5kAzDS4le9JwLWE,iv:sL0mHg3W4+vmh3Gtrb7OqHvN9WX+s/TDf6NGKemW2aU=,tag:fQDHR7ZuR3tyBFzge5LWEw==,type:str]
    version: ENC[AES256_GCM,data:5w==,iv:v/YjMFgRyZvENtKqK64eHFUg1u+9FVE+yO2sY73zd2w=,tag:JCj9RSXjInpL2rGaJXUDFg==,type:str]
    deviceUuid: ENC[AES256_GCM,data:cEhV1beMbbAy362V2Wx9CNTl0ucamVJRgG4=,iv:v2wiz49NhJCxePlGHLMjauyBOwKqWMLvKoAe9gE0jtY=,tag:LGDeJ5JvseUgPVUHIJDwZg==,type:str]
    uniqueKey:
      alg: ENC[AES256_GCM,data:xODwsUBm3g==,iv:r3EWQz2o/peBPVc/MHARL129z8wvWiuSKRh70q0Tnmk=,tag:xmfpKJq5X7ZFPZXfjBGPWw==,type:str]
      ext: ENC[AES256_GCM,data:C1TFnw==,iv:v0Wa4gKOhsuxzcmiZ0ZKwqfxRBRPizOf+oR1ZAxDgmc=,tag:s528wd+sTl3m2vPpclJBAg==,type:bool]
      k: ENC[AES256_GCM,data:/THKIaqAfxmAsWyoOutW8umT2QnGA0GIUK+wPKiE/V96hfXugkCuCdKuLg==,iv:+3v5srA4+LjNSv2DQG2Y/zXJqd09snTnjhTMoiYtwNg=,tag:14OZi9fcaEp4vmxJ2/J34g==,type:str]
      key_ops:
        - ENC[AES256_GCM,data:DkUDhC7wVg==,iv:rMTGJEZV6T/SZqlTua6tTAQ6PpZG9NCqouGwyvep2Zk=,tag:7EAH7aCyuIdpd5QeKBZc7g==,type:str]
        - ENC[AES256_GCM,data:cIbekwYGuA==,iv:45eff20Y8ZC98wrR7cm9y/9IbXQUbpIaWevTTpg5XKQ=,tag:DapZOjMsLOAiH8BE0s58Dg==,type:str]
      kty: ENC[AES256_GCM,data:azDX,iv:hIF/Fu6yArJofJgnD3A+ngGruos2Oz+tIHB3kk/vWCA=,tag:7haWHJ8oPCRF+z+JBtQMmA==,type:str]
      kid: ENC[AES256_GCM,data:o4TUiiuyBI1vMBW3wwv4AOAefdTgK/EX4Ck=,iv:8sw9z2JqI+sEaS8F6iiV1c6ccq1Fn7nzO6G5d+/EQV0=,tag:dU8rLg3YFXq1AJxzfKUvOg==,type:str]
sops:
  age:
    - recipient: age1dlagmajl96rsfff84arhj2dd97kpy64wjp6dxgjftvm8v0fy2erspglp3s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3azhJU0hJS21pS0tpNTNL
        MkhpSmJ0L2ozV1Q4L1lodzhXdXQvT2ZDQUFRCjA2VjQ4MHhiaVRvcVZ0aXg0ek1r
        M0RDZGk2eGljQThkc2RKTkNMYmtPSVEKLS0tIDAwck4vRU5Ccy9udVN6SFQza3Nq
        OE5JUEtRck52amtWV2RCWEYwYXRGSjQKkDSFd685XeECMU2qMO/o7RP14N+fDKs5
        +BUMPMKBAbHPY0sJ+XNynvU7aerGXh5U/Vt4ZwQaZeoRgd+8FwuxPA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T22:44:59Z"
  mac: ENC[AES256_GCM,data:17t8vJhDAUoTeO5Rz8rdZORdJPKPQpD9x434gDOVU636EiEDdQLIObMtMRX3MVVIODP1KGOgct1ABK6vrQMSHvF1oTwq7bMrtjls7sc1xle7H6nFnF7ujiegSL+33jC733AXGK18scLKGsptZQobr4AEb6xJ3z8WeVN5KU8YGlE=,iv:5rzcO1AciTWNq8rKVigairAYk2OlKe99Si+2tpguTu4=,tag:b5qiF8b1Oj1u//1Bd7DKRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
