apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-secret
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:GTdbIHxcTJUggxk3ie2zJpinSs8qscVy2GgYYTQkec6zqwB2BX8nSvG7Uf2sAnPBqsKvAx1CFrppAqllHhttLiXuHXekikOSfRKD9DEV2nQhXFmXIpwm1KRs7lEqQFKZsvGrKL3RYIHng17YXdXABrBMZRsh6isFBDgZQE4IXMgjYOSaujOz8YLnw/NdYLOW+ca3fAoEeRQU9EB6asuM7maFyrmmbtpnzDIGhx17aY55AHrIkDqQ3Ty8AYAE+im330+fdFzJe63TEa2rj8qKgCUMF14hp35djYqbhLO7sr22hPnQk0Qd06AKvsF5D3LYl2kd58wZIWkslxMPHXSUof9AWTNwd7U0mxJsgXXgOpWuvOEXJZpdOuwpG3WF/Xf7BMFIFh/s0Vd7nSC7t8/pShCoiYP6RZ4viT3LwpoxSHrnHQ0lYOws95YaGAT7aR5hqzxiNshfnSnpZDCLFrJLU1cjdlxuEp+7G1xmTLiQn5EuJ3eVq/CMxJX8qjX7h+RGOSax4/ickE3ddtoPm8tYOzDJjUyb6EVyZNKvZLv91Yh9tNz0vqZJfimOo8O56cppwgm/tZMOf78Oi6ylidq2L/4YdEbhc3btAInvLOmKb6fqoIivdc4v7l3clMJ3a3//WG6maUZn7Y+kMhW8yt6ZX9QTbkBumOisLxJLCnXpCb1jOmI+1G0BLE94NNtfDwkqmVDyjtQFiz/i01kaDhTu3MN0OS1uk9zWdXB34Z23jWfrrN3yQoJmu69yUApZol2a/IBtFJfo6yVYsAawf3s4P2MeOg9sSWx1PZSpUpX+oylWyTrL6PKulQmzXwcSG8wiO1SxySwMY5lfgy5mA1zkBxRt5Dog6LTN1WyJnKFKS+JfO6bThmwlmwNiqi0kDj7lUzuNbBFh71utcvthlR9u60+SFLE+J3DHCdvGJlNYT8mHdH4GSMlX0C8EqZLF8WhLoPnLrTyoAjGxF7frINIlng6QdCo0ZvjdV5TRa6cMyezsYR0uhxEmG6FAYSAas2iBWP0F8+9E+rDF+ucjFN7coGClEiiURTDOHQ1RVgwZXSMOKdiadfkdV18NIgFUCwWix6qlpax5OHQ0GrW6zTGopLLz3BjMF8rXCu9vnU/JrKfKVeKTEL8b/6w3SJ3Nw9VE0SWzci3Aztz5UJM7Yue5xGIZ/xyvS/4MxC+Pv4qPr8z+HC/5diDiZ/1KQDP9yaQa+GDbSVGFNzF4RmB/MxfANQUpvhjsgNl8ysfa/whDDjULDZOWFAG/O8oJs8ql3tPBegJ/JaYb+WxtGx+T7dG3VyrwbkucTryJ0PkAucgyx+SmX+iKZS+atuzqjdNaJYVg1ExK5CSvfu1dsRCvhhckDbMZwk1yC0+K829m9KWgmkWiny8sOa44Rid954KcQLET7USSxqBJE0PoXn1EMjtm7tnhrlxV3TdA4Gw1VxVX4Ik=,iv:89nHZkYZx0YZJCqTaVqQ8o3Otwaa9ynEjJsYVsAX9hQ=,tag:aZHZqzxq8ahzx29z26tIXA==,type:str]
sops:
  age:
    - recipient: age180c6h75uq6h3p46s6y4h6uqm0k42exnqepudc5yrnkg6h97vuyzqnexxd3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcERMNVlYajRrRlpXYXEx
        U1VUNmxvbGpSMi9IT1ZyVmZ3dDJEMXQrWnhrCjkxNUpsTU9sY0I4YlI4bzY5OUVo
        Ym54WjFIdWhjTXBNUVNoY3dMRkhPUTAKLS0tIEE3TXVVTFlxMWFieHlLdm15Ukc1
        c2RSSDNGMGJ5NFpuOFc3RjlhWjI3Y1kKZlF1Vc5X9W7BPawgFqzpUkAlSFPmjT1m
        prEmGFARLy3NTQ34wfCI5/kZOPsVjaAZsFCcUV1jbqoe2Cfw0XBCDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T20:41:08Z"
  mac: ENC[AES256_GCM,data:TdaIMSfBYBR85P8D0sbCts6ct6SXJxoD+piCp4UJd6/fc/fb/j7elPcT7S8SdOwrDN4xIwISVruWF+YGnZ6XQ+CN10dmsbwY2vLGwyLfzNNBOTWGXB3ylL8cYNjEcYelUl1Ys+yRw6VJ6J+oL4SkTKjpvlmPoPIh7S/Rc5qhBw0=,iv:aX40wILrwqmtNvX90j1sA7ROLVsFvuAqDT/KlyZL46s=,tag:bVpfHSAI5FjFI3FztoLXyw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0