apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-secret
  namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:Tl50FKfVQ4r8Cp5tZRyLIdKLDm2nhGpcXHu2KvIPFSwRMOjk21G93NvIrrueeyCi6GpWky3sIR7rDsMS5fhUM2130wyVuAiKrXVk50lhSsWVDpNw05PYXXTdcgTOInJuHUDEbfkbTINSwsaMxANbOhGkjP8unltq6356VP/eYWrZuxGYk7A+/vtD5XnSh2MUviTcf1U7yQ1tQgE9TUUUnl9wTLmKgoGZLOdZbIaBl22MAkdmsHAcIdsHzIB/wotTQaINz16tRuA/1UpQFiBkSkisqP5vL6sUvI1dP/4RX0TEbUaouJn82f/nVpi5RFs3woJb2D6cO8SiB49gOR2c/gPMGZRMQNkJK3OIuna1g08LB4JhIvdXA8FjcZcPz8e8w1cF6vnGFiVrCrM6NPv6k/evI0Ek7iiJTz8IHne69RMF+DVzMlMDly0NV3Eh7RXfnMazKvXMPK3Bg4Y1vGLzbzyXar3BUNn0M06bexNe4J2YA6+s56hsNd062rjrUq90/qXNfM8gof7DMeVSrpKVgprGT/Kb9rffQGreSK5+IDOqjOrijiumDZav6Zk0ykl+aILpnvv5F8YBqMBt9L0Ui93sPHaziQ0JCra9lwxQIvzdCdVpNyzGhu1G/b0JBAGXyyANVVqoy9UX5D1cJOZW17BiSqUlSOQvE6bLixodcs80N4bNkChcfq+xRnEywE5oAmGm4TmAb3dSeTtjrrvVmIHpcHlLuWVTvRyMsPOtCyCAhI2z9sLHHNSXQPvGpk2EnwNQFC8zh2zRKeNCgHqUZzHPwhasY1GB4/r56HSYJrc71HVRumaaPq/383QaAVI1Xh7HHiD1d0Rkh3M8sSqOktX8TW+e6X9N5OAEw6QPkaFeeyZ6Il9RyLECIoDb0Q9WanGJD+6f4GfxbUpTAiZUvk0JjaGt/KtGrGTtrO3W6ZFvs0yla8XGbFjmtlwDIsnluDVvH7UltbRCrPMjAPrDj8w6gfEUG/rErwdB124qCEzBIa/RkM+U4sBSoEhblG0kYrtY9Bj4nnIQOUBoEi/OndKhEB7pooxY0TRTeV7Z2yJOmJh1vdnFTSL8/6le58+Ey0VuL8lZrqAHC7t8EnexUnFEmv1EMk0QWIQNXphekQK4KH5+rWG/zM86U3VTCAfUoEHz6T1lYJ/6Fl1hLvdHJLUMU52iY7DyMclZLmRnIAPLfbFtAoYdZ3uGvwSA09QRh0wkPwN8ufIPkWKiP7lVVIvFdHR7DfOrTts8iMXGe4gKIwo6TRNnWagZdJNG9Vva2F4Mw0IZDA0CV4e11MYhVt4kXJipclOw34Dn0nwVhgUM2tcueFYE8sPAHs0eU0626CeJz25tGHmgj5D+OHJAHEzJ+9MEJ36IeTTEmF09jE5AyNe9Cv0ju5dFh0KmsTeKUSelQYc6GmPsz1gUIphxFJ00xfA6IuJ+uzjZBg4bq1uk1Q==,iv:V6FLJEKSJr46WwdjCuz41859t+I8rLVV7utfdCFI6eM=,tag:Tvt13n3XR5+cWLhvF8jMBw==,type:str]
sops:
    age:
        - recipient: age180c6h75uq6h3p46s6y4h6uqm0k42exnqepudc5yrnkg6h97vuyzqnexxd3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcFZ2RXlLSUFQL21LQVNu
            L3h4bStMb2dhQW05aEhHWDZ5Q1Q2aUxqUzBJCnp3YjN1U2tJRHFNTStiRlZtanBI
            czBocUxLRzk5NlVVWXA1TDlnMUlYczAKLS0tIFV2VGNSVzdtYkJKM3lwTEtkZmNZ
            c0VrdlBZVmErS09pZUZWTTk0YnZMb1kKmFmU8wMPdJCIMIZ9VBwXxB1ud8eD0Z3k
            9Cn1p8O6hBV29y1pXWbwCYZ3NyPpo2UsJGPYW5GeKn9Rdp2fVu8XZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T20:21:45Z"
    mac: ENC[AES256_GCM,data:axCfxuV3DD+tCztGvAWmZ2xZt18SKbSZKlv3KlQO4A3SuetbtxPUiHvg8zdESgsUcqcsV4boSVXWAFL3oJGKaPpnmfjQ8MsTQpQyz1vdFhJDA3ScO4/Oj/xeHG+xXaA2OcIArXMaQiNC2UK9/uRwsXQqEcoxJpFzTCnwJKp6tFQ=,iv:iGDUvsh/kkJDERrbbyCI3TQgXhgy7L3cjJ5KFvNDeIc=,tag:GVHnmU3wpd9XYs+VMRZb3w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
