apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-secret
  namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:eyJ2ZXJpZmllciI6eyJzYWx0IjoiNmItVlpVY0M1U3Rpc1lTUjhwcmwyUSIsImxvY2FsSGFzaCI6ImVhUVdaa1ZJWEZWVElVUl9iVG1ETGUxRHNBYmQtU2xsODZSN3VoU0tPYzAifSwiZW5jQ3JlZGVudGlhbHMiOnsia2lkIjoibG9jYWxhdXRodjJrZXlraWQiLCJlbmMiOiJBMjU2R0NNIiwiY3R5IjoiYjUrandrK2pzb24iLCJpdiI6IlJkck1PalROOWd6aVVyRG4iLCJkYXRhIjoiLWtrazFFVHB2Y3cwd2Z5NjRkZnJmN1Z4QUpXdFlzUmlBTVFKY2g5SFdEWG4tUVFtdmpUdVREZFZKbm94NGRzR0ZWOXJ6UW5paDdsc2N1bE5zWmlqUGZKTzN5U3puMVEwbURac0tXY0tsRENQZHdRWll5SEF3dFUyZVgxYWxNT21pNFd0S1ZIZFhPb1ZrU0RTYzYtamFXSURQSTlMbi1yN2VfZGl1eDdiVjkxODZjUTRCY1ZWM05BMFlWRzBFb25rY2FuWHFwYW9UYUZvNlpvbk9DLUg2NjBlbDdzUk52cXlZZk1mRlN5eWpTNndrYUJWVFRvVkJULWFkZldXQjhEb3NiRC1xMXNGcmFyUGJQNzA4S2ctSXg5V0RsZVNxdnFEWV90NWxYRG9FcTRnYm9zbXZVYUpLSlloT1ZTaGZiTjhGcVQwdnl1NUtHUzlVb2tXOXZLT1dKTVZrQ1Y1ejVoV1BiNVNOcGlPSTAzem1VUWRqa244ak5vTUFYQlFDRG1wOGZmTWlhTkl2aFBndnZaUmd1dWVfWmxjY3VFZDdaUUhOaFRNVUVzRTc1d19fZ2owME5UNlFYY25IWUxWRnl0ckFqSUFnR08xQ1J0MHQydkp2c1ktck1KZG5ER1QwU3NLaGtXLVIwZ0ktZFc4NEMzQVdwYkRDS3FJSXdLenVmM2NhTWdIdmgyYmlraDNsRGdnYzYxY2RUOTl2UXZyRXpYcE9XU3Vyck5tMEFCcTdkS2VJRnNwLUdRaEozSk1zcTJSeWFqZlNmVUlNMDlZNmtadkg0YVczV0E1YjFNdGhSc3lnRUpWR1pqZFFuOEpyX1NIVjF5R3NvSTlrbnhnd3hDQ0pnIn0sInZlcnNpb24iOiIyIiwiZGV2aWNlVXVpZCI6Inpwd2ozaW43Y241bW9qZm9peXV4YmRvcjY0IiwidW5pcXVlS2V5Ijp7ImFsZyI6IkEyNTZHQ00iLCJleHQiOnRydWUsImsiOiJrYndWODJDQ240NlZJY0Z1Um1mUnNWdWVtRTA4cjIyNktwVDFrUHhONldrIiwia2V5X29wcyI6WyJlbmNyeXB0IiwiZGVjcnlwdCJdLCJrdHkiOiJvY3QiLCJraWQiOiI1MmhlN2ltNTJxeG1mdGc1cWJlZGloNWhmdSJ9fQ,type:str]
sops:
    age:
        - recipient: age180c6h75uq6h3p46s6y4h6uqm0k42exnqepudc5yrnkg6h97vuyzqnexxd3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITWtmQmxCMnJMYVUreHVt
            L1VwN0QrRFlRMEVVU05IeTRLRWp4RUo0L1NBCkUzVVlLMGlCaCtHQ3lGcUpQN2VB
            YW9EbWlvRkNhTjVYVC92R2NsQU51cUUKLS0tIGhkVHhUaXliWEIzMUhCY3ROWFpT
            aEpaQXY5d3U2V2FWbERVaHNCWXlOWWcKg9IispVAJ2nyYyahyeo2c3CEPsFQjYgm
            P+C3Z7qT/gV1Wa6A5a2vt1FG7VWeYXa5kFKJg4EApfddwFxQ0em19Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T00:51:45Z"
    mac: ENC[AES256_GCM,data:IfExh/7XoO5LnkRTJzLK3KOp74fM3v+AVZwKieYJA8oOVq3FEk7ahnkOlPbgNdK3Kalqyqmh8+2Qw1wWK5YJHIzPkWZINM91yVmoRKNp+X2UBsPbfP/elsD9kcjMuQ/+ShZrvNZBcnud3FQUMmn19lSyREBqZlj6DvMa2PQ04TM=,iv:WSDtkvEIcg2nwwwD5g6S7AD4JgItvy7170uGIrQzStA=,tag:dxEMdf/HWDHED05O+ahxfg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
