apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:kFplqVigaI7p/z1KiuMJOGxJ+Jgl8MeU8Ip1Epl5FcyqNpDYFP1dEQ==,iv:KOWfdPQRn+amtq+JyDwasHKecvJbX58tioPMTSCeJ98=,tag:DHi3nzn2rm1Vg0hM+pNo/w==,type:str]
sops:
  age:
    - recipient: age1dlagmajl96rsfff84arhj2dd97kpy64wjp6dxgjftvm8v0fy2erspglp3s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TEN6RjhjOStPOHF2dUw0
        YVc1QnpFTVh5TGMwWlpzVkZ3YWZLbWl0bVI0CmpCYTZEUFMwcTQzcWRGcmF0bFhq
        SEV4SzRWejU2NGQrbFB6L1pTQXY1TkUKLS0tIDlkUzBQVVBOZFZ6ZHN2WXgxV1dF
        blBOTWE3WlpzQjk3T0E2eEtnM2s1VFkKZP5i9Bn79N3zpuRurpX3aCPSN35ARKsg
        paKWgrLI3FN82oJ4ScKEf1X8P4rkkR/2LJuzBq9+zyxpkNA1kdiGYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T01:18:18Z"
  mac: ENC[AES256_GCM,data:BjUF6UI8Bo6+UZG8Xn31T/rdFHvHGCDabSBddpL2l55R3o/oh86kzgkhnmiPOgnZyQUXe4JHVdncIf+PpMAhwS+o+JWJoG2jf4rHIUaUlY0fsSvmnWcl/ZpODYwbr3xqBMnFHMpkiIbORSJxHDdvEJFXWE+ceIZ14duvIeOdReA=,iv:IBwKtY7m9NqFq7Mo2KbjzeoDeiMK5Fnt2vscfzfG+t4=,tag:6j4WFyXgIMfrFs9jR2S9zQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
