apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:RMvM+kEx92C9UndzllsOjAGh+edZrbywTWouW4V3nU3RcnYdzBVW/Q==,iv:bu8g7v3F24lTH7YewISVIeONnvWF0brsm9aW8UZFGxM=,tag:mrUWwB15fo75UjmD3AM4BQ==,type:str]
sops:
  age:
    - recipient: age1dlagmajl96rsfff84arhj2dd97kpy64wjp6dxgjftvm8v0fy2erspglp3s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoY1k2WDNLY1pvRzZKN2sz
        bWtOUHdKSW9sR0xrVGV3MEFOc3dnc2ZwVW53CkdXTm13eVdIQ0VkTXhKbksrWlgw
        UzJWejdEY2xGR29ZSWoySU5vUUVlUXMKLS0tIEdzNkx4aXhQNkZIZ2RGZDJhcHFF
        Ykx2ZmQ4TTkvK3cxZldVT2p0eWV6RlEKxJ4exUdr5TcDR/DfaAzyHyAVgtKvnzhV
        xn6lstz2qbLO9OuswvhWJvOUVxmI5vaI8TibxWhRaCB1QqfLnHf4Mg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T01:16:47Z"
  mac: ENC[AES256_GCM,data:ISKrGOLZBpDZmzG+o7NyRb8h9Txd7q+4EfHJ89PyIeG9q3UMC9at8StV/FNGog+MaJiUD4dx/qoj+es3R55ym/NLbBFTC2wgZx5x/dNUahnG3OSSJiQMxRyxiuFu3irmO4KXT+ooGs/QcDmYdBZaRblNe/5z+TvGhK+KlfbWWjM=,iv:OEm3D6TmTtaF/gnOeR2W7P5Dm4QHjXrOcZ8nSGjYD6I=,tag:DgTgX7TXuewigclrwBQ2HA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
