apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Qo1O9pjOaBiEz3PJoE9Wq27TboOpWpkj36uY6QdxCIRc/dPy1JH1Uw==,iv:Rk7b8bI536AtCBmrMSIHGyq7pSLsFlCmOfCjuDp6D0U=,tag:0RFZg7egsvex2151eCcJQQ==,type:str]
sops:
  age:
    - recipient: age1dlagmajl96rsfff84arhj2dd97kpy64wjp6dxgjftvm8v0fy2erspglp3s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISXA1Y3NLM2UrRVJRTUlS
        NHN1bFNIV2xOTVllQ2NhOTVFNi80R1FER0IwCnZJZ1NEM0x3RFRaL0JtakNSYmtK
        S1FzdVRLZHhFalpZdlE0a080cXhYUDgKLS0tIER4a2MvbkxveDhiSVJobUFBUXdl
        Y0RyQldqQzBwbnpSQnY5QzZBODNZRWcKHJzDvb+IjeQDjTEfI7QXqP8rnwAHvpw6
        5/gEkOLN68kySSlzXG46l0CDwsyMBjAf/6QrbRCFIbmabkluFAISeA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T00:20:52Z"
  mac: ENC[AES256_GCM,data:K+c+sYfxAB4llMUsQURrVx/hhnx1vzwoYwX9urS00XS2sRWnLoPhr2CS7i6wAPFCSxv0v2XPJlCc/OeqlS/M6MnoUGIfRcUSufcIeQbmUA5ETZYq86cmQJpqM66KKCN6cByGbcuhkl+HXG9sJaP1zG0kIxRkjktiTBaY5NUcUVs=,iv:eQqf2vMWidQYogaNwL4bCcxS4m3aaTNTULUz3/pOw6U=,tag:GVP7bX76hHQvk49HILO4DA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
