apiVersion: v1
kind: Secret
metadata:
  name: external-dns-unifi-secret
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:8NihttgU1go=,iv:BMsE9I1f5J3x2AgM6QsVdPomwyqUVnRvbRoIrYa9Vs4=,tag:WxPhZ0020ezWdrjBTQSQng==,type:str]
sops:
  age:
    - recipient: age1dlagmajl96rsfff84arhj2dd97kpy64wjp6dxgjftvm8v0fy2erspglp3s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YTEreVZqWjhyeUJVT3kx
        cHRCQk1LL29OUTlFNmR0Y2NHQUR6ODVrSUg0CjRtTWkvZXl3aHFNTEhCOG1PSnNn
        VnBHNjZDaEFicGQvdzJnV1JUY09hRTQKLS0tIHZwZWMwOGlHUWJHdWtremhaSEhX
        NlZVOTBKRWI1YVhhNWxXRUZPeGlMWTAKOp39rTJCm2YIdVUpoj4+kDu7IMm8QF4o
        eEZJNk6DagVuPr+r6eIVI+BoiAUxkLmSXEebUZcv51DRnjdkF9oNVg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-21T02:03:09Z"
  mac: ENC[AES256_GCM,data:XTj20tAIzJv85a85g55S/B3+gdw4O4p4yHvuDlIfv3+CWG1IkzT/VnUwJVmJcvEcWva70/mEJxModYHiaGrYHao+GED8y8ZXQeKAzYEWK60rFEDY9pUiRqz8O6O+mqGnKBVYIFCrRC7amNkqPi6YapAehxRFnfQvdQNfM+a0muM=,iv:PfAmSSQgXD4b1PAQEhLZr33MbWo1Oxxg513LE/4ARQQ=,tag:3nKWHA41+mc+lSvqc+EtdA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
